### ISSUE TITLE
S3 storage is not compatible with Django 1.11

### ISSUE THREAD

**Issue by jmurty** [ixc/ixc-whitenoise#1]
The `ixc_whitenoise.CompressedManifestStaticFilesStorage` storage implementation does not seem to be compatible with Django version 1.11.

I haven't looked into this deeply at all, but on a 1.11 project I saw errors where url handling method calls failed due to the wrong number of arguments. I worked around it for now in the project by deleting the `STATIC_STORAGE = 'ixc_whitenoise.CompressedManifestStaticFilesStorage'` setting inherited from https://github.com/ixc/ixc-django-docker

**Comment by mrmachine** [comment]
This should be fixed in 5c189c6
